chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('chat-room/<int:user_id>/', views.chat_room, name='chat_room'),
    path('ajax/<int:user_id>/', views.ajax_load_messages, name='chatroom-ajax')
]

otrs_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('school/', include('school.urls')),
    path('teacher/', include('teacher.urls' )),
    path('', include('chat.urls')),
    path('', include('notification.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.Homepage, name='home-page'),
    path('registerteacher/', views.RegisterTeacher, name='register-teacher'),
    path('registerschool/', views.RegisterSchool, name='register-school'),
    path('login/', views.Login, name='login-user'),
    path('logout/', views.Logout, name='logout-user'),
    path('delete-user/', views.delete_user, name='delete_user'),
    # path('pay/', views.pay, name='pay'),
    path('update-user-paid-status', views.update_user_paid_status, name='update_user_paid_status'),


    #reports
    path('reports/', views.reports, name='reports'),
    path('create-pdf', views.pdf_report_create, name='create_pdf'),

    #users Password reset
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='users/password/password_reset.html'), name='reset_password'),
    path('reset-password-sent/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password/password_reset_form.html'), name='password_reset_confirm'),
    path('reset-password-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_complete'),
]

teacher/models.py
from django.db import models
from users.models import User
from school.models import Newjob



# Teacher resume model 
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    phonenumber = models.CharField(max_length=20)
    subject = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    idnumber = models.IntegerField()
    dob = models.DateField()
    description = models.TextField(default=False)
    image = models.ImageField(upload_to='profile_pics')
    resume = models.FileField(upload_to='resumes')
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'), ('O', 'Other'),)
    gender = models.CharField(max_length=100, choices=GENDER_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    
    

# application model
class Application(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    newjob = models.ForeignKey(Newjob, on_delete=models.CASCADE)
    application_date = models.DateTimeField(auto_now_add=True)
    STATUS_CHOICES = (('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'))
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='Pending', null=True)


    def __str__(self):
        return str(self.teacher)

users/models.py
from django.contrib.auth.models import AbstractUser, Group,Permission
from django.db import models

class User(AbstractUser):

    USERNAME_FIELD = 'username'
    username = models.CharField(max_length=150, unique=True)
    is_teacher = models.BooleanField(default=False)
    is_school = models.BooleanField(default=False)
    groups = models.ManyToManyField(Group, blank=True, related_name='custom_user_set')
    user_permissions = models.ManyToManyField(Permission,blank=True,related_name='custom_user_set')
    has_paid = models.BooleanField(default=False)

    has_resume = models.BooleanField(default=False)
    has_school = models.BooleanField(default=False)  

    created_at = models.DateTimeField(auto_now_add=True)

users/views.py
import json
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import User
from school.models import Newjob
from django.core.paginator import Paginator
from datetime import datetime
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
import calendar
from teacher.models import Application

from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from intasend import APIService




token = "ISSecretKey_test_51fcb535-e653-46aa-8484-61b089b30bfc"
publishable_key = "ISPubKey_test_6cdb65b0-a6df-45db-bc60-22fa01987909"
service = APIService(token=token, publishable_key=publishable_key, test=True)





# homepage
def Homepage(request):

    jobs = Newjob.objects.all().select_related('school').order_by('-created_at')

    # get search parameters from users
    search_subject = request.GET.get('subject')
    search_location = request.GET.get('location')
    search_school_type = request.GET.get('school_type')

    #compare the value taken from select input with one in the database 
    if search_subject:
        jobs = jobs.filter(subject=search_subject)
    if search_location:
        jobs = jobs.filter(school__location=search_location)
    if search_school_type:
        jobs = jobs.filter(school__school_type=search_school_type)

    #pagination for availbale teachers
    page = Paginator(jobs, 60)
    page_list = request.GET.get('page')
    page = page.get_page(page_list)

    #pass the context (page, search subject, search loaction and search school type )to the html
    context={'page':page, 'search_subject':search_subject, 'search_location':search_location, 'search_school_type':search_school_type}
    return render(request, 'users/home.html', context)




# register teacher
def RegisterTeacher(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        is_teacher = bool(request.POST.get('is_teacher'))

        # check whether user with same email already exists
        if User.objects.filter(email=email).exists():
            messages.warning(request, 'Email already exits')
            return redirect('register-teacher')

        # check whether user with same username ready exists
        if User.objects.filter(username=username).exists():
            messages.warning(request, 'Teacher already exits')
            return redirect('register-teacher')

        # create new user
        new_user = User.objects.create_user(email=email, username=username, password=password)
        new_user.is_teacher = is_teacher
        new_user.has_resume = False
        new_user.save()

        messages.success(
            request, 'Your account has been created successfully. Please log in.')
        return redirect('login-user')

    return render(request, 'users/registerteacher.html')




# registerschool
def RegisterSchool(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        is_school = bool(request.POST.get('is_school'))

        # check whether the user with same email alredy exits
        if User.objects.filter(email=email).exists():
            messages.warning(request, 'Email already exits')
            return redirect('register-school')

        # check whether school with the same username already exits
        if User.objects.filter(username=username).exists():
            messages.warning(
                request, 'School name already exits. Enter a unique school name')
            return redirect('register-school')

        # create new user
        new_user = User.objects.create_user(email=email, username=username, password=password)
        new_user.is_school = is_school
        new_user.has_school = False
        new_user.save()


        messages.success(
            request, 'Your account has been created successfully. Please log in.')
        return redirect('login-user')
    
    return render(request, 'users/registerschool.html')




# login
def Login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

          # Authenticate user
        user = authenticate(request, username=username, password=password)

        if user is not None:
                login(request, user)
                if user.is_teacher:
                    return redirect('teacher_home')
                elif user.is_school:
                    return redirect('school_home')
            
    
        else:
            messages.warning(
                request, 'Invalid Credentials. Please enter the correct username and password')          
    
    return render(request, 'users/login.html')




# logout
def Logout(request):
    logout(request)
    return redirect('home-page')



#delete user
def delete_user(request):
    user_id = request.GET.get('id')
    user1 = get_object_or_404(User, id=user_id)
    user1.delete()
    return redirect('home-page')

    
#view monthly reports
@login_required
@staff_member_required
def reports(request):

    if request.method == 'POST':
        date = request.POST.get('date')
    else:
        date = datetime.now().strftime('%Y-%m')    # Set the default value to the current month
        
    month1 = int(date.split('-')[1])
    year1 = int(date.split('-')[0])

    month2 = calendar.month_name[month1]


    teacher1 = User.objects.filter(is_teacher=True)
    teachers_created_this_month = []
    for teach in teacher1:  
        if teach.created_at.date().month == month1 and teach.created_at.date().year == year1:
            teachers_created_this_month.append(teach.teacher)
            
            
    job1 = Newjob.objects.filter()
    jobs_created_month = []
    for job2 in job1:
        if job2.created_at.date().month == month1 and job2.created_at.date().year == year1:
            jobs_created_month.append(job2)

        
    month_app = []
    applications = Application.objects.all()
    for app in applications:
        if app.application_date.date().month == month1 and app.application_date.date().year == year1 :
            month_app.append(app)


    context ={'teachers_created_this_month':teachers_created_this_month, 'jobs_created_month':jobs_created_month,  'month2':month2, 'year1': year1, 'month_app':month_app, 'date':date}
    return render(request, 'users/reports/reports.html', context)



# generate pdf report
@login_required
@staff_member_required
def pdf_report_create(request):
    if request.method == 'POST':
        date = request.POST.get('date')
    else:
        date = datetime.now().strftime('%Y-%m')    # Set the default value to the current month
        
    month1 = int(date.split('-')[1])
    year1 = int(date.split('-')[0])

    month2 = calendar.month_name[month1]


    teacher1 = User.objects.filter(is_teacher=True)
    teachers_created_this_month = []
    for teach in teacher1:  
        if teach.created_at.date().month == month1 and teach.created_at.date().year == year1:
            teachers_created_this_month.append(teach.teacher)
            
            
    job1 = Newjob.objects.filter()
    jobs_created_month = []
    for job2 in job1:
        if job2.created_at.date().month == month1 and job2.created_at.date().year == year1:
            jobs_created_month.append(job2)
            
       
    month_app = []
    applications = Application.objects.all()
    for app in applications:
        if app.application_date.date().month == month1 and app.application_date.date().year == year1 :
            month_app.append(app)

    template_path = 'users/reports/pdfreport.html'
    context ={'teachers_created_this_month':teachers_created_this_month, 'jobs_created_month':jobs_created_month,  'month2':month2, 'year1': year1, 'month_app':month_app}
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="'+ month2 +' reports.pdf"'
    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(
       html, dest=response)
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response
    

# def pay(request):

#     response = service.collect.mpesa_stk_push(phone_number= '254703156845', email='vchalloh@gmail.com', amount=1, narrative='purchase')

#     print(response)
#     invoice_id = response['invoice']['invoice_id']
#     phone_number = response['customer']['phone_number']

#     print('invoice_id:', invoice_id)
#     print('phone_number:', phone_number)


#     return render(request, 'users/pay.html')


def update_user_paid_status(request):
    bd=request.body
    data = json.loads(bd) 
    user_id = data['id']
    print(user_id)
    
    user = User.objects.get(id=user_id)
    print(user)
    user.has_paid = True
    user.save()
    return JsonResponse({'status': 'success'})

templates/users/reports/pdfreport.html
{% load static %}

<div >
    <img src="{% static 'images/1.jpeg' %}" class="card-img-top" alt="Testimonial Image 1">
    <h2 style="justify-content: end ;">ONLINE TEACHER RECRUITMENT SYSTEM</h2>
    <h2 style="justify-content: end;">OTRS GENERAL REPORTS</h2>
</div>
<hr>
<!-- teachers joined in july -->
<div class="container">
    <div class="card px-sm-4 my-3 pb-3 table-responsive">
        
        <div>
            <h1 class="text-center mt-3">TEACHERS JOINED IN {{month2}} {{year1}}</h1>
        </div>
        <table class="table table-bordered bg-body-secondary ">
            <thead>
                <tr class="bg-primary">
                    <th>Full name</th>
                    <th>Phone number</th>
                    <th>Subject</th>
                    <th>Location</th>
                    <th>Id number</th>
                    <th>DOB</th>
                    <th>Gender</th>
                    <th>Data Joined</th>
                </tr>
            </thead>
            <tbody>
                {% for teacher in teachers_created_this_month %}
                <tr>
                    <td>{{teacher.fname}} {{teacher.lname}}</td>
                    <th>{{teacher.phonenumber}}</th>
                    <td>{{teacher.subject}}</td>
                    <td>{{teacher.location}}</td>
                    <td>{{teacher.idnumber}}</td>
                    <td>{{teacher.dob}}</td>
                    <td>{{teacher.gender}}</td>
                    <td>{{teacher.created_at | date}}</td>
                    
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>
<hr>
<!-- jobs in july -->
<div class="container">
    <div class="card px-sm-4 my-5 pb-3">
        <div>
            <h1 class="text-center mt-3">JOBS POSTED IN {{month2}} {{year1}}</h1>
        </div>
        <table class="table table-bordered bg-body-secondary ">
            <thead>
                <tr class="bg-primary">
                    <th>subject</th>
                    <th>School</th>
                    <th>Date Posted</th>
                    <th>Salary</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for job in jobs_created_month %}
                <tr>
                    <td>{{job}}</td>
                    <td>{{job.school}}</td>
                    <td>{{job.created_at | date}}</td>
                    <td>{{job.salary}}</td>
                    
                   
                    
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>
<hr>
<!-- Application on each job -->
<div class="container">
    <div class="card px-sm-4 my-5 pb-3">
        <div>
            <h1 class="text-center mt-3">ALL APPLICATIONS IN {{month2}} {{year1}}</h1>
        </div>
        <table class="table table-bordered bg-body-secondary ">
            <thead>
                <tr class="bg-primary">
                    <th>subject</th>
                    <th>School</th>
                    <th>Applications</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for job in jobs_created_month %}
                <tr>
                    <td>{{job}}</td>
                    <td>{{job.school}}</td>
                    <td>
                        <table class="table table-bordered bg-body-secondary text-small">
                            <thead>
                                <tr>
                                    <th>Teacher</th>
                                    <th>Application Date</th>
                                    <th>status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for application in job.application_set.all %}
                                <tr>
                                    <td>{{application.teacher.teacher.fname}} {{application.teacher.teacher.lname}}</td>
                                    <td>{{application.application_date|date}}</td>
                                    <td>{{application.status}}</td>                            
                                </tr>
                                
                                {% endfor %}
                            </tbody>
                        </table>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>
<hr>

templates/users/reports/reports.html
{% extends 'users/base.html' %}

{% block content %}

{% load static %}

<div class="container mt-4">
    <div class="row ">
        <div class="my-2">
            <h3>Select month you want to view reports for</h3>
        </div>
        <div class="col-md-3 me-0">
            
            <form action="" method="POST">
                {% csrf_token %}
                <input type="month" name="date" value="{{ date }}" class="form-control">
                <!-- Your other form fields -->
               <button type="submit" class="btn btn-primary my-2">View Reports</button>

              </form>
        </div>
        <div class="col-md-3 ms-auto">
            <form action="{% url 'create_pdf' %}" method="POST">
                {% csrf_token %}
                <input type="month" name="date" value="{{ date }}" class="form-control" hidden>
                <!-- Your other form fields -->
               <button type="submit" class="btn btn-light">Generate Report</button>
              </form>
    
        </div>
    </div> 
</div>

<!-- teachers joined in july -->
<div class="container">
    <div class="card px-sm-4 my-3 pb-3 table-responsive">
        <div>
            <h1 class="text-center mt-3">Teachers joined in {{month2}} {{year1}}</h1>
        </div>
        <table class="table table-bordered bg-body-secondary ">
            <thead>
                <tr class="bg-primary">
                    <th>Full name</th>
                    <th>Phone number</th>
                    <th>Subject</th>
                    <th>Location</th>
                    <th>Id number</th>
                    <th>DOB</th>
                    <th>Gender</th>
                    <th>Data Joined</th>
                </tr>
            </thead>
            <tbody>
                {% for teacher in teachers_created_this_month %}
                <tr>
                    <td>{{teacher.fname}} {{teacher.lname}}</td>
                    <th>{{teacher.phonenumber}}</th>
                    <td>{{teacher.subject}}</td>
                    <td>{{teacher.location}}</td>
                    <td>{{teacher.idnumber}}</td>
                    <td>{{teacher.dob}}</td>
                    <td>{{teacher.gender}}</td>
                    <td>{{teacher.created_at | date}}</td>
                    
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>

<!-- jobs in july -->
<div class="container">
    <div class="card px-sm-4 my-5 pb-3">
        <div>
            <h1 class="text-center mt-3">Jobs posted in {{month2}} {{year1}}</h1>
        </div>
        <table class="table table-bordered bg-body-secondary ">
            <thead>
                <tr class="bg-primary">
                    <th>subject</th>
                    <th>School</th>
                    <th>Date Posted</th>
                    <th>Salary</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for job in jobs_created_month %}
                <tr>
                    <td>{{job}}</td>
                    <td>{{job.school}}</td>
                    <td>{{job.created_at | date}}</td>
                    <td>{{job.salary}}</td>
                    
                   
                    
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>

<div class="container">
    <div class="card px-sm-4 my-5 pb-3">
        <div>
            <h1 class="text-center mt-3">applications in {{month2}} {{year1}}</h1>
        </div>
        <table class="table table-bordered bg-body-secondary ">
            <thead>
                <tr class="bg-primary">
                    <th>subject</th>
                    <th>School</th>
                    <th>Applications</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for job in jobs_created_month %}
                <tr>
                    <td>{{job}}</td>
                    <td>{{job.school}}</td>
                    <td>
                        <table class="table table-bordered bg-body-secondary text-small">
                            <thead>
                                <tr>
                                    <th>Teacher</th>
                                    <th>Application Date</th>
                                    <th>status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for application in job.application_set.all %}
                                <tr>
                                    <td>{{application.teacher.teacher.fname}} {{application.teacher.teacher.lname}}</td>
                                    <td>{{application.application_date|date}}</td>
                                    <td>{{application.status}}</td>                            
                                </tr>
                                
                                {% endfor %}
                            </tbody>
                        </table>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>




{%  endblock %}